import os

LINKS = "https://www.flexjobs.com/"
ROOT_PATH = os.getcwd()
DATA_PATH = "DATA"
DRIVER_PATH = "DRIVER"
LINK_PATH = "LINK"
INFO_PATH = "INFO"
PRO_PATH = "TRACK_PROGRESS"
IMAGE_PATH = "IMAGE"
FILE = "raw_data.json"
MINI_WAIT = 1
WAIT = 20
MEDIUM_WAIT = 120
LONG_WAIT = 240